export enum ORDER_STATUS {
  PENDING = 'PENDING',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}
export const OrderStatusList = [
  ORDER_STATUS.PENDING,
  ORDER_STATUS.DELIVERED,
  ORDER_STATUS.CANCELLED,
];
